### PR TITLE
Modify rtconfig Junos behaviour to match Cisco 

### PR DESCRIPTION
**Pull request by darylc**
- AND community & prefix lists rather than OR'ing them.

### CODE REVIEW

**Comment by darylc** [comment]
Is this one good to merge?

**Comment by nickhilliard** [comment]
The idea is fine, but there are merge conflicts with this patch.  Can you sort these out so that the pull can be merged cleanly?

Also, could you write a couple of lines for the rtconfig man page to decribe what the CLI flag does?

**Comment by darylc** [comment]
I've updated the man page for this and -junos_replace.

This should merge ok now.

**Comment by nickhilliard** [comment]
the updated patch removes the -ciscoxr_use_prefix_lists command-line switch.  If this is intentional, could you move this to a separate pull request?

**Comment by darylc** [comment]
The code for -ciscoxr_use_prefix_lists was commented out, so it was just a cleanup.  Sorry I should have mentioned that in the pull request

**Comment by nickhilliard** [comment]
if -ciscoxr_use_prefix_lists should be disabled, could you submit this as a separate patch and remove it from this pull request?  CiscoXRConfig::usePrefixLists is still defined in f_ciscoxr.cc and .hh.

**Pull request merged**
